---
- name: Basline Config
  hosts: all
  vars:
  - build_dir: build_dir
  - config_dir: config_dir
  tasks:
  - template: src=baseline.j2 dest=build_dir/{{inventory_hostname}}/base.conf
    check_mode: no
    changed_when: false
