---
- name: Collect Show Bootvar info from all Devices and save to file
  hosts: all
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - ios_command:
      commands: show bootvar
    register: facts
  - copy:
      content: "{{facts}}"
      dest: "{{results}}/{{inventory_hostname}}.json"
