---
- name: REPORT ONLY
  hosts: all
  vars:
  - results: results
  tasks:
  - include_vars: "{{results}}/{{inventory_hostname}}.yml"
  - file: path={{results}} state=directory
    run_once: true
  - lineinfile:
      dest: "{{results}}/bootvar.log"
      regexp: "{{inventory_hostname}}"
      line: "{{'%-20s %8s'|format(inventory_hostname,facts.stdout)}}"
