---
- name: Collect Show Bootvar info from all Devices and save to file
  hosts: all
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - ios_command:
      commands: show bootvar | include bootflash
    register: facts
  - ios_facts: provider={{ios_provider}}
    register: info
  - lineinfile:
      dest: "{{results}}/bootvar.log"
      regexp: "{{inventory_hostname}}"
      line: |
        {{'%-20s %8s'|format(inventory_hostname,facts.stdout)}}
        {{'%-20s %8s'|format(inventory_hostname,ansible_net_image)}}
